#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout

user:
  path: /boutique/mon-profil/{id}
  controller: App\Controller\UserInterfaceController::index